### ISSUE TITLE
能否支持国家图书馆的民国图书

### ISSUE THREAD

**Issue by SukSuk1986** [deweizhu/bookget#10]
如题，请问能否支持国家图书馆的民国图书下载，十分感谢！

http://202.106.125.224/allSearch/searchDetail?searchType=&showType=1&indexName=data_416&fid=16jh003641

**Comment by deweizhu** [comment]
注意访问的网址，用read.nlc.cn这个域名打开是可以的。
http://read.nlc.cn/allSearch/searchDetail?searchType=&showType=1&indexName=data_416&fid=16jh003641

下载URL是：
http://read.nlc.cn/OutOpenBook/OpenObjectBook?aid=416&bid=90942.0

**Comment by SukSuk1986** [comment]
十分感谢，另外是否考虑支持[抗日战争与近代中日关系文献数据平台]，功德无量，再次感谢！(https://www.modernhistory.org.cn/)https://www.modernhistory.org.cn/#/

**Comment by deweizhu** [comment]
已新增支持：https://github.com/deweizhu/bookget/releases/tag/v1.2.4
说明文档见：https://github.com/deweizhu/bookget/wiki/04-%E6%94%AF%E6%8C%81%E7%9A%84%E5%9B%BE%E4%B9%A6%E9%A6%86URL

**Comment by SukSuk1986** [comment]
您好，有多分册的情况好像后面分册的无法下载，即便是点开后面分册也是下载第一册。另外是否资助的方式啊？https://www.modernhistory.org.cn/#/DocumentDetails_qk?fileCode=0008_qk_00908&title=%E5%B9%BF%E5%B7%9E%E9%93%B6%E4%B8%9A%E9%80%9A%E8%AE%AF&flag=false

**Comment by deweizhu** [comment]
报纸、期刊初版并不支持，11月25日更新才支持的。请下载 https://github.com/deweizhu/bookget/releases/tag/v1.2.5
另外，此帖已经关闭，一个主题请开一个新帖，谢谢。
捐赠方式在 https://github.com/deweizhu/bookget/wiki/SPONSOR （已经放在项目首页上，可以见到）
