### ISSUE TITLE
不知可否新增“全国包括索引”

### ISSUE THREAD

**Issue by SukSuk1986** [deweizhu/bookget#11]
不知可否新增“全国包括索引”
https://www.cnbksy.com/login

![图片_20231206230232](https://github.com/deweizhu/bookget/assets/121573057/00ab9808-b2d5-4e98-81a4-7307ccc6dbc0)

可能需要通过地方图书馆跳转过去登陆，例如广州中山图书馆https://www.zslib.com.cn/index.html

**Comment by SukSuk1986** [comment]
明白的，但是全国报刊里面有不少民国的报纸，本应没有版权的，是否可以考虑一下？

**Comment by deweizhu** [comment]
类似读秀、超星等平台，和各高校、或图书馆合作的，他们之间或许有商业关系。
这一部分的内容，不在考虑范围之内。如果你可以手工下载，请使用人工下载。
