### ISSUE TITLE
普林斯頓大學圖書館掛了

### ISSUE THREAD

**Issue by zheyuanchenarthistorian** [deweizhu/bookget#12]
試圖抓取的是這個《北齋漫畫》https://catalog.princeton.edu/catalog/9916871943506421
鏈接符合格式但沒有反應。使用的是1.2.6版本。但是在“支持的url”內提供的普林斯頓大學的一樣格式的鏈接還是可以運行的。不知道是什麼問題？

**Comment by deweizhu** [comment]
網頁左下角有一個IIIF圖標，你可以手動點開它，複製網址即可下載。
```
https://figgy.princeton.edu/concern/scanned_resources/b7b38129-0454-4167-9211-6706b95e1c33/manifest
```
