### ISSUE TITLE
是否可以增加“民國美術文獻庫”

### ISSUE THREAD

**Issue by zheyuanchenarthistorian** [deweizhu/bookget#13]
https://dlibgate.cafa.edu.cn/mgmswx
中央美术学院的“民国美术文献库”，有大量稀见晚清民国艺术文献，不知道可不可以增加抓取功能？
感谢！
如果遇到无权访问，需要手动改变地址。比如https://dlibgate.cafa.edu.cn/mgmswx/item/7451-n-a?offset=15是进不去的，但是改成：http://222.28.16.145/viewer/7451/?offset=17#page=3&viewer=picture&o=&n=0&q=就可以进了，
需要从http://222.28.16.145/ebook/picture?search=&sort=-ReleaseDate,_score&perpage=50&page=1& 进入

**Comment by deweizhu** [comment]
技术上可以实现，但不敢写。
有些提示：
```
受版权保护，该资源仅限图书馆内访问。

请到图书馆或分馆数字阅读空间阅览。

阅览数字资源，请遵守《中华人民共和国著作权法》、《信息网络传播权保护条例》及相关法律、法规和政策。
```
