### ISSUE TITLE
国图 矢量古籍下载

### ISSUE THREAD

**Issue by h1storreson** [deweizhu/bookget#2]
国图矢量古籍能批量下载吗？单独下载一旦册数巨大工作量也成被增加。最麻烦的是矢量古籍不会自动排序，二三百册排序工作量太大了

**Comment by deweizhu** [comment]
有对照阅读的PDF，可以同时下载影像、矢量了，会生成两个文件夹。已发布1.2.1版。

**Comment by h1storreson** [comment]
感谢您的开发！
