### ISSUE TITLE
是否有可能加入其他在线电子书阅读网站，如Hyreader？

### ISSUE THREAD

**Issue by c20050817** [deweizhu/bookget#4]
感谢作者的开发，实在帮助良多！
不过像其他在线阅读电子书的网站，是否也可以做到提取pdf呢？不知是否可以套用同相似编程？（本人码盲，纯粹大胆提出~

**Comment by deweizhu** [comment]
基本上都是定制化开发，一个网站要写一次。需要会golang编程，二次开发，才可以添加其它网站支持。

**Comment by deweizhu** [comment]
基本上都是定制化开发，一个网站要写一次。不能复用。近期没有新增网站的计划，保持现有功能稳定即可。
