### ISSUE TITLE
[中国]台北古籍与特藏文献

### ISSUE THREAD

**Issue by h1storreson** [deweizhu/bookget#6]
該圖書館古籍不再支持下載了嗎？我下載不了了
https://rbook.ncl.edu.tw/NCLSearch/Search/SearchDetail?item=c746191282414a7386410a47ee1d0c67fDcwODYyNQ2&page=3&whereString=&sourceWhereString=&SourceID=0&HasImage=

**Comment by deweizhu** [comment]
1.2.1版，測試可以下載。但是，該網站有封禁IP的功能，大約下載100多頁的時候，會不能下載，而此書有 3652 頁。
方法一：頻繁更換新IP，可在被封IP後，繼續下載。
方法二：使用`bookget -speed=5 `延時5秒，或許可以延長下載時間。

**Comment by h1storreson** [comment]
收到，谢谢
