### ISSUE TITLE
韩国国立中央图书馆下载错误

### ISSUE THREAD

**Issue by goforit211** [deweizhu/bookget#7]
您好！首先感谢您开发这个图书下载工具，最近我在下载韩国国立中央图书馆图书的时候，出现了这样一个问题，书的前几页正常下载，剩下全部变成90b的无内容文件，不知是怎么回事？前几天的时候都能正常下载全部内容的。
谢谢！
![截屏2023-08-07 11 36 43](https://github.com/deweizhu/bookget/assets/141600289/61df4343-83c1-48c4-988e-68b7d2f18333)

**Comment by deweizhu** [comment]
经测试，韩图服务器可能有限制，短时间内下载太快了。对于出错的文件，可以删除，再下载一次。
如果需要限速功能，可以重下载1.2.1版，每页等待3秒中，模拟真人浏览图书，或可以解决。
使用如下命令启动软件：
```
bookget -speed=3 "https://lod.nl.go.kr/page/CNTS-00048001521"
```

**Comment by goforit211** [comment]
> 经测试，韩图服务器可能有限制，短时间内下载太快了。对于出错的文件，可以删除，再下载一次。 如果需要限速功能，可以重下载1.2.1版，每页等待3秒中，模拟真人浏览图书，或可以解决。 使用如下命令启动软件：
> 
> ```
> bookget -speed=3 "https://lod.nl.go.kr/page/CNTS-00048001521"
> ```

您好，设置限速下载后，可以正常下载全部内容了，十分感谢！

**Comment by goforit211** [comment]
另有一问题，比如一套书有好几个分

> > 经测试，韩图服务器可能有限制，短时间内下载太快了。对于出错的文件，可以删除，再下载一次。 如果需要限速功能，可以重下载1.2.1版，每页等待3秒中，模拟真人浏览图书，或可以解决。 使用如下命令启动软件：
> > ```
> > bookget -speed=3 "https://lod.nl.go.kr/page/CNTS-00048001521"
> > ```
> 
> 您好，设置限速下载后，可以正常下载全部内容了，十分感谢！

但是发现下载其他的书，限速之后还是只能下载前面几页，不知道该如何解决这个问题。。speed最大可以设置成多少呢？
而且我就算设置了下载那本书的后面几页（一开始显示90b的），还是无法正常下载，不知该怎么办？

**Comment by deweizhu** [comment]
是服务器作的限制，但不知限一个IP能请求多少次，遇到不能下载的时候，可以换个时间段、或换一个IP再试。一本书可能要分几次下载。

**Comment by goforit211** [comment]
> 是服务器作的限制，但不知限一个IP能请求多少次，遇到不能下载的时候，可以换个时间段、或换一个IP再试。一本书可能要分几次下载。

好的，感谢！我再多试几次看下！

**Comment by goforit211** [comment]
另外，不知可否追加首尔大学图书馆（https://lib.snu.ac.kr）的下载方式，比如下面这个图书：
https://snu.alma.exlibrisgroup.com/view/UniversalViewer/82SNU_INST/12748596580002591?xywh=-974,-156,3972,3103&r=0
之前我用chrome一个插件dezoomify可以下载单页，但是无法批量下载，比较麻烦。
谢谢！

**Comment by deweizhu** [comment]
图书馆太多了，加不完。近期不会更新软件。
你可以自己动手寻找IIIF Manifest。如你举的例子，那本书用bookget下载的URL是：
```
https://snu.alma.exlibrisgroup.com/view/iiif/presentation/82SNU_INST/12748596580002591/manifest?iiifVersion=2
```
通过右键【查看网页源代码】能看到。或者在页面左下角找Share图标，点开后有灰色的IIIF图标，点击它，也可以得到下面网址。

```
https://snu.alma.exlibrisgroup.com/view/iiif/presentation/82SNU_INST/12748596580002591/manifest?iiifVersion=3
```
把最后一个 3 改为 2 就可以下载了。

**Comment by goforit211** [comment]
另外，想问一下，奎章阁的书，如何下载其中几个分册呢？
https://kyudb.snu.ac.kr/book/view.do?book_cd=GC02555_00
比如这个书有3000多本，我只想要下载其中几册，按照您说的分册下载参数，比如只下2916册，bookget -vol=2916 （？）这样子输入的话，他还是从第1册开始按顺序下载，不知应该如何操作呢？Powershell那个for循环可以用在奎章阁的书上吗？

**Comment by deweizhu** [comment]
奎章阁的PDF，不需要使用bookget也可以下载，你往下拉就看到PDF按钮，点开弹窗按需下载。
另外，一个问题开一个话题，此话题已关闭。
