### ISSUE TITLE
[Arch Linux] 将 bookget 打包到 AUR 仓库 

### ISSUE THREAD

**Issue by taotieren** [deweizhu/bookget#9]
[AUR bookget-git](https://aur.archlinux.org/packages/bookget-git) 在 PKGBUILD 中我将 `bookget` 安装到 `/usr/bin/bookget` 配置文件安装到 `/etc/bookget/` 下
```bash
    install -Dm755 build/${pkgname%-git} -t ${pkgdir}/usr/bin/
    install -Dm0644 "${srcdir}/${pkgname%-git}/LICENSE" -t "${pkgdir}/usr/share/licenses/${pkgname%-git}/"
    install -Dm0644 "${srcdir}/${pkgname%-git}/cookie.txt" -t "${pkgdir}/etc/${pkgname%-git}/"
    install -Dm0644 "${srcdir}/${pkgname%-git}/config.ini" -t "${pkgdir}/etc/${pkgname%-git}/"
```
源码中对 `cookie.txt` 和 `config.ini` 查找的路径需要修改什么吗？
如果修改的话需要修改哪里呢？能否给出参考吗？谢谢。

**Comment by deweizhu** [comment]
配置文件只需要config.ini 即可。
https://github.com/deweizhu/bookget/blob/master/config/conf.go 第142行
```go 
cfg, err := ini.LoadSources(ini.LoadOptions{IgnoreInlineComment: true}, root+string(os.PathSeparator)+"config.ini")
#更改为：
cfg, err := ini.LoadSources(ini.LoadOptions{IgnoreInlineComment: true}, "/etc/bookget/config.ini")
```

cookie.txt、urls.txt 不是必须的，可以删除。是用完即弃的文件。
可以使用命令行指定路径。如不指定，默认在【当前工作目录】下查找
```shell
bookget -c="cookie.txt"  -i="urls.txt"
```

**Comment by taotieren** [comment]
感谢解答，config.ini 按上述修改，

> ```shell
> bookget -c="cookie.txt"  -i="urls.txt"
> ```

按 linux 规范的话这两个文件应该配置到 /var/ 下。否则可能会出现权限报错的问题，
